//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ScreenshotBrower.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ScreenshotBrower.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap detail_head {
            get {
                object obj = ResourceManager.GetObject("detail_head", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon favicon {
            get {
                object obj = ResourceManager.GetObject("favicon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找 System.Drawing.Bitmap 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Bitmap list_head {
            get {
                object obj = ResourceManager.GetObject("list_head", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似于 (图标) 的 System.Drawing.Icon 类型的本地化资源。
        /// </summary>
        internal static System.Drawing.Icon logo {
            get {
                object obj = ResourceManager.GetObject("logo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 function oAddContent(text)
        ///{
        ///	var nodep=document.createElement(&apos;p&apos;);
        ///	var node2=document.createElement(&apos;span&apos;);
        ///	node2.style=&quot;display: inline-block;margin-left: 400px;&quot;;
        ///	node2.innerText=text;
        ///	
        ///	var node=document.createElement(&apos;h2&apos;);
        ///	node.innerText=document.URL;		
        ///	node.append(node2);	
        ///	node.append(nodep);
        ///	node.append(nodep.cloneNode(true));
        ///		
        ///	document.body.firstChild.before(node);	
        ///	document.body.lastChild.after(node.cloneNode(true));
        ///	
        ///	document.getElementById(&apos;skiplink&apos;).remove();
        ///} 的本地化字符串。
        /// </summary>
        internal static string oAddContent {
            get {
                return ResourceManager.GetString("oAddContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 function oChange(num)
        ///{
        ///		document.getElementById(&apos;nav-packard-glow-loc-icon&apos;).click();//open dialog	
        ///		setTimeout(function()
        ///		{
        ///			document.getElementById(&apos;GLUXChangePostalCodeLink&apos;).click(); //click change
        ///		},2000);	
        ///		setTimeout(function(){
        ///			document.getElementById(&apos;GLUXZipUpdateInput&apos;).value=num; //input num
        ///		},4000);	
        ///		setTimeout(function(){
        ///		document.getElementById(&apos;GLUXZipUpdate-announce&apos;).click();//change
        ///		},6000);		
        ///		setTimeout(function(){
        ///		document.querySelector(&apos;button[nam [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string oChange {
            get {
                return ResourceManager.GetString("oChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 83707
        ///83706
        ///83705
        ///83704
        ///83703
        ///83702
        ///83701
        ///83680
        ///83669
        ///83642
        ///83634
        ///83616
        ///74965
        ///74964
        ///74960
        ///74931
        ///74457
        ///63559
        ///63546
        ///63540
        ///63533
        ///63501
        ///42753
        ///42742
        ///42741
        ///42728
        ///42720
        ///42715
        ///50858
        ///50849
        ///50846
        ///50837
        ///50002
        ///74965
        ///74964
        ///74960
        ///74931 的本地化字符串。
        /// </summary>
        internal static string zip {
            get {
                return ResourceManager.GetString("zip", resourceCulture);
            }
        }
    }
}
